#! /bin/bash

. ~/.bash_aliases
shopt -s expand_aliases
ciao

. src/functions.bash

mkdir -p data
cd data

for obsid in $(obsids)
do
    files=evt1,bpix,pbk,msk,flt,asol,bias,stat,mtl
    instrument $obsid | grep -qi hrc && files=evt1,bpix,msk,flt,asol,dtf
    download_chandra_obsid $obsid $files
done
